# Lists cloze completions to look over by hand, as a Markdown file:
#   1. flagged as pasted / copied (with what the source looks like)
#   2. polished, generated-sounding completions that are not flagged
#   3. every all-caps completion
#   4. every single-word completion (except bare numbers)
# For each unique completion: how many sessions typed it, and how many of
# those pass the participant-level screens (not incomplete, not a repeat
# participant, native English speaker, US citizen and resident).
#
#   Rscript shared/cloze_review/list_screens.R      (from the repo root)
#
# Output: shared/cloze_review/screen_lists.md

library(tidyverse)
library(here)
source(here("analysis", "analysis_data.R"))
source(here("shared", "common_schema.R"))

d <- load_analysis_data(default_analysis_settings)
session_screens <- d$sessions |>
  transmute(session_id,
            passes_participant_screens = !if_any(all_of(d$participant_steps)),
            repeat_participant = step_2_repeat)

cloze <- read_csv(here("combined", "cloze.csv.gz"),
                  col_types = cols(study = col_character(), cloze_item = col_character(), .default = col_guess())) |>
  mutate(response = coalesce(response, "")) |>
  inner_join(session_screens, by = "session_id", relationship = "one-to-one")
stopifnot(nrow(cloze) == nrow(read_csv(here("combined", "cloze.csv.gz"), show_col_types = FALSE)))

completions <- cloze |>
  summarize(sessions = n(), pass_screens = sum(passes_participant_screens), repeats = sum(repeat_participant),
            .by = c(study, cloze_item, response, cloze_code, cloze_nonsense, cloze_nonsense_reason)) |>
  mutate(n_words = str_count(str_squish(response), "\\S+"),
         all_caps = str_count(response, "[A-Za-z]") >= 2 & !str_detect(response, "[a-z]")) |>
  arrange(study, as.integer(cloze_item), str_to_lower(response))
stopifnot(!anyDuplicated(select(completions, study, cloze_item, response)))

pasted <- read_cloze_pasted_text(here("shared", "cloze_pasted_text.csv")) |>
  mutate(study = as.character(study), cloze_item = as.character(cloze_item))
with_pasted <- completions |>
  left_join(pasted, by = c("study", "cloze_item", "response"), relationship = "one-to-one")

md_escape <- function(x) str_replace_all(str_squish(x), "\\|", "\\\\|")
md_table <- function(df) {
  header <- paste0("| ", paste(names(df), collapse = " | "), " |")
  rule <- paste0("|", paste(rep("---", ncol(df)), collapse = "|"), "|")
  rows <- apply(df, 1, \(row) paste0("| ", paste(md_escape(row), collapse = " | "), " |"))
  c(header, rule, rows, "")
}
nonsense_label <- function(flag, reason) if_else(flag, reason, "no")
as_rows <- function(df, ...) {
  df |>
    transmute(item = paste(study, cloze_item, sep = "/"), completion = response, ...,
              sessions, `pass screens` = pass_screens, `current code` = cloze_code,
              `nonsense now` = nonsense_label(cloze_nonsense, cloze_nonsense_reason))
}

# Completions only repeat participants typed are excluded already: not listed.
with_pasted <- filter(with_pasted, sessions > repeats)
completions <- filter(completions, sessions > repeats)
flagged <- with_pasted |> filter(cloze_nonsense_reason %in% c("pasted_text", "copied_context"))
generated <- with_pasted |> filter(pasted %in% FALSE)
all_caps <- completions |> filter(all_caps)
# Bare numbers are always nonsense (by rule), so they are not listed.
single_word <- completions |> filter(n_words == 1, !str_detect(response, "^[0-9[:space:][:punct:]]+$"))

summary_line <- function(df) {
  sprintf("%d unique completions from %d sessions; %d of those sessions pass the participant screens (%d are repeat participants).",
          nrow(df), sum(df$sessions), sum(df$pass_screens), sum(df$repeats))
}

lines <- c(
  "# Cloze completions to look over",
  "",
  "Generated by `shared/cloze_review/list_screens.R`. *sessions*: how many sessions typed this exact",
  "completion; *pass screens*: how many of them pass the participant-level screens (complete, not a",
  "repeat participant, native English, US citizen and resident). *nonsense now*: the current",
  "`cloze_nonsense_reason` (or \"no\"). Completions typed only by repeat participants are left out",
  "(they are excluded already).",
  "",
  "## 1. Pasted or copied (currently flagged)",
  "",
  "`pasted_text` judgments come from `shared/cloze_pasted_text.csv` (source type in *what*, judged by",
  "reading; not checked against the web). `copied_context` is the rule for a word-for-word piece of the",
  "prompt's first sentence.",
  "",
  summary_line(flagged), "",
  md_table(as_rows(flagged, what = coalesce(note, "copied from the prompt's first sentence (rule)"))),
  "## 2. Polished, generated-sounding, not flagged",
  "",
  "Read as likely AI-generated (fluent, list-like, generic), but not clear enough to flag without a",
  "decision. All 2024.",
  "",
  summary_line(generated), "",
  md_table(as_rows(generated)),
  "## 3. All caps",
  "",
  summary_line(all_caps), "",
  md_table(as_rows(all_caps)),
  "## 4. Single words",
  "",
  "Bare numbers are left out: they are always nonsense.",
  "",
  summary_line(single_word), "",
  md_table(as_rows(single_word))
)
writeLines(lines, here("shared", "cloze_review", "screen_lists.md"))
message("Wrote screen_lists.md: ", nrow(flagged), " flagged, ", nrow(generated), " generated-sounding, ",
        nrow(all_caps), " all caps, ", nrow(single_word), " single words")
